version: '3.4'

services:
    test_db:
        image: postgres
        expose:
            - 5432
        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql/data
        env_file:
            - .env

    backend:
        container_name: manual-deploy-backend
        build:
            .
        volumes:
            - /opt/app/node_modules
        ports:
            - 8000:8000
        depends_on:
            - test_db
        env_file:
            - .env
